kind: pipeline
type: docker
name: gitea release change log test
trigger:
  event:
    - tag
platform:
  os: linux
  arch: amd64
steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: test
    image: hb0730/drone-plugin-gitea-release-change-log
    settings:
      debug: true
      url:
        from_secret: gitea-server
      token:
        from_secret: gitea-token