kind: pipeline
type: docker
name: gitea release change log test
trigger:
  event:
    - push
  branch:
    - main

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:1.16
    environment:
      GO111MODULE: "on"
    commands:
      - go get -v -t -d ./...
      - go build -v -ldflags '-X main.version=${DRONE_BUILD_NUMBER} ' -a -o drone-plugin-gitea-release-change-log .
  - name: docker build
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - ls
      - docker build -t drone-plugin-gitea-release-change-log .
  - name: test
    image: drone-plugin-gitea-release-change-log
    settings:
      debug: true

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock